enum TOKEN {
    PLUS, MINUS, TIMES, SLASH, LPAREN, RPAREN,
    SEMICOLON, COMMA, PERIOD, BECOMES, EQL, NEQ,
    LSS, GTR, LEQ, GEQ, BEGINSYM, CALLSYM, CONSTSYM,
    DOSYM, ENDSYM, IFSYM, ODDSYM, PROCSYM, THENSYM,
    VARSYM, WHILESYM, NUMBER, IDENT, UNKNOWN
};

